
// identifier types
giERROR_TYPE = -1
giQUOTE_TYPE = 1
giQUASI_QUOTE_TYPE = 2
giUNQUOTE_TYPE = 3
giSPLICE_QUOTE_TYPE = 4
giWITH_META_TYPE = 5
giDEREF_TYPE = 6
giLIST_TYPE = 7
giVECTOR_TYPE = 8
giHASH_MAP_TYPE = 9
giNUMBER_TYPE = 10
giSTRING_TYPE = 11
giSYMBOL_TYPE = 12
giKEYWORD_TYPE = 13
giNIL_TYPE = 14
giTRUE_TYPE = 15
giFALSE_TYPE = 16

// tokens
giTAB_TOKEN = 9
giNEWLINE_TOKEN = 10
giSPACE_TOKEN = 32
giCOMMA_TOKEN = 44
giPERIOD_TOKEN = 46
giTILDA_TOKEN = 126
giAT_TOKEN = 64
giCURLY_OPEN_TOKEN = 123
giCURLY_CLOSE_TOKEN = 125
giBRACKET_OPEN_TOKEN = 91
giBRACKET_CLOSE_TOKEN = 93
giPAREN_OPEN_TOKEN = 40
giPAREN_CLOSE_TOKEN = 41
giSINGLE_QUOTE_TOKEN = 39
giBACKTICK_TOKEN = 96
giCARTOT_TOKEN = 94
giDOUBLE_QUOTE_TOKEN = 34
giBACKSLASH_TOKEN = 92
giCOLON_TOKEN = 58
giSEMICOLON_TOKEN = 59

// error reason
giILLEGAL_TOKEN_ERROR = -1
