#!/usr/bin/env sh
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

set -eu

root=$(CDPATH= cd "$(dirname "$0")" && pwd)
. "$root/src/csound-env.sh"

if [ "$#" -gt 0 ]; then
  case "$1" in
    /*) script=$1 ;;
    *) script=$PWD/$1 ;;
  esac
  shift
  set -- "$script" "$@"
fi

cd "$root"
exec "$CSOUND" -n -d -m128 --orc src/run.orc -- "$@"
