#!/usr/bin/env sh
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

set -eu

root=$(CDPATH= cd "$(dirname "$0")" && pwd)
csound_bin=${CSOUND:-csound}
case "$csound_bin" in
  /*) ;;
  */*) csound_bin=$PWD/$csound_bin ;;
esac
if [ "$#" -eq 0 ]; then
  echo "usage: $0 SCRIPT [ARG ...]" >&2
  exit 2
fi
case "$1" in
  /*) script=$1 ;;
  *) script=$PWD/$1 ;;
esac
shift

# The reference interpreter loads env.mal and core.mal relative to this directory.
cd "$root/mal/impls/mal"
exec "$csound_bin" -n -d -m128 "--env:INCDIR=$root" \
  --orc "$root/src/run.orc" -- "$root/mal/impls/mal/stepA_mal.mal" \
  "$script" "$@"
