#!/usr/bin/env sh
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

MAL_ENV_CONSTRUCTOR=MalMkStep6Env exec "$(dirname "$0")/run-step3-env"
